name: 'Compile'
run-name: ${{ github.ref_name }}
on: workflow_dispatch

jobs:
  build:
    name: Compile
    runs-on: windows-latest

    env:
      Solution_Name: "Source/DynamicTradeInterface/DynamicTradeInterface.sln"
      Name: DynamicTradeInterface

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - name: Set configuration
      run: | 
        if ($env:Branch -eq "refs/heads/master") {
          echo "Configuration=Release" >> $env:GITHUB_ENV
        } else {
          echo "Configuration=Debug" >> $env:GITHUB_ENV
        }
      env:
        Branch: "${{ github.ref }}"
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
     
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name
      
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ env.Configuration }}

    # Remove unnecesary directories
    - name: Cleanup
      run: | 
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "Source"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "*.md"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue ".*"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "LICENSE.txt"

    - name: Generate artifact name
      run: |
        $branch = ""
        if ("${{ env.Configuration }}" -ne "Release") {
            $branch = $env:Branch.replace("refs/heads/", "") + "_"
        }
        echo ArtifactName="$env:Name-${{ env.Configuration }}_$branch$(get-date -f MM-dd)" >> $env:GITHUB_ENV
      env:
        Branch: "${{ github.ref }}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ArtifactName }}
        path: ${{ github.workspace }}/**/*
