name: 'Compile'
run-name: ${{ github.ref_name }}
on: workflow_dispatch

jobs:
  build:
    name: Compile
    runs-on: windows-latest

    env:
      Solution_Name: "Source/DynamicTradeInterface/DynamicTradeInterface.sln"
      Name: DynamicTradeInterface
      Versions: "1.4;1.5"

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
     
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name
      
    - name: Build
      run: | 
        "${{ env.Versions }}".Split(";") | ForEach {
          msbuild $env:Solution_Name /p:Configuration=$_
        }

    # Remove unnecesary directories
    - name: Cleanup
      run: | 
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "Source"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "*.md"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue ".*"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "LICENSE.txt"

    - name: Generate artifact name
      run: |
        $branch = ""
        if ("${{ env.Branch }}" -ne "master") {
            $branch = $env:Branch.replace("refs/heads/", "") + "_"
        }
        else
        {
            $branch = "Release"
        }
        
        echo ArtifactName="$env:Name-$branch_$(get-date -f MM-dd)" >> $env:GITHUB_ENV
      env:
        Branch: "${{ github.ref }}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ArtifactName }}
        path: ${{ github.workspace }}/**/*
