name: 'Compile'
run-name: ${{ github.ref_name }}
on: workflow_dispatch

jobs:
  build:
    name: Compile
    runs-on: windows-latest

    env:
      Solution_Name: "Source/DynamicTradeInterface/DynamicTradeInterface.sln"
      Name: DynamicTradeInterface
      Versions: "1.4;1.5"

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@main

    - name: Setup NuGet
      uses: NuGet/setup-nuget@main
     
    # - name: Restore NuGet Packages
    #   run: nuget restore $env:Solution_Name
      
    - name: Build
      run: | 
        "${{ env.Versions }}".Split(";") | ForEach {
          msbuild $env:Solution_Name -t:restore,build /p:Configuration=$_
        }

    # Remove unnecesary directories
    - name: Cleanup
      run: | 
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "Source"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "*.md"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue ".*"
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "LICENSE.txt"

    - name: Generate artifact name
      run: |
        $branch = ""
        if ("${{ env.Branch }}" -ne "refs/heads/master") {
            $branch = $env:Branch.replace("refs/heads/", "") + "_"
        }
        else
        {
            $branch = "Release"
        }
        
        echo ArtifactName="$env:Name-$branch_$(get-date -f MM-dd)" >> $env:GITHUB_ENV
      env:
        Branch: "${{ github.ref }}"

    - name: release
      if: ${{ env.Branch == 'refs/heads/master' }}
      uses: softprops/action-gh-release@v2
      env:
        Branch: "${{ github.ref }}"
      with:
        generate_release_notes: true
        files: ${{ github.workspace }}/**/*
        name: ${{ env.ArtifactName }}
        make_latest: true

    - name: Upload build artifacts 
      if: ${{ env.Branch != 'refs/heads/master' }}
      uses: actions/upload-artifact@main
      env:
        Branch: "${{ github.ref }}"
      with:
        name: ${{ env.ArtifactName }}
        path: ${{ github.workspace }}/**/*

